name: a
version: '1.0-SNAPSHOT'
main: org.fc.a.A
api-version: '1.21'

commands:
  lv:
    description: Set target level

  spawn:
    description: Spawn target

  delete:
    description: Delete target

  move:
    description: Change target movement pattern

  mode:
    description: Change game mode
